# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrew/opencvWorkspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrew/opencvWorkspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrew/opencvWorkspace/CMakeFiles /home/andrew/opencvWorkspace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrew/opencvWorkspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named ExtraterrestrialBodies

# Build rule for target.
ExtraterrestrialBodies: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExtraterrestrialBodies
.PHONY : ExtraterrestrialBodies

# fast build rule for target.
ExtraterrestrialBodies/fast:
	$(MAKE) -f CMakeFiles/ExtraterrestrialBodies.dir/build.make CMakeFiles/ExtraterrestrialBodies.dir/build
.PHONY : ExtraterrestrialBodies/fast

#=============================================================================
# Target rules for targets named Mesh

# Build rule for target.
Mesh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mesh
.PHONY : Mesh

# fast build rule for target.
Mesh/fast:
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/build
.PHONY : Mesh/fast

#=============================================================================
# Target rules for targets named Quaternions

# Build rule for target.
Quaternions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Quaternions
.PHONY : Quaternions

# fast build rule for target.
Quaternions/fast:
	$(MAKE) -f CMakeFiles/Quaternions.dir/build.make CMakeFiles/Quaternions.dir/build
.PHONY : Quaternions/fast

#=============================================================================
# Target rules for targets named 3x3Matrices

# Build rule for target.
3x3Matrices: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3x3Matrices
.PHONY : 3x3Matrices

# fast build rule for target.
3x3Matrices/fast:
	$(MAKE) -f CMakeFiles/3x3Matrices.dir/build.make CMakeFiles/3x3Matrices.dir/build
.PHONY : 3x3Matrices/fast

#=============================================================================
# Target rules for targets named 3dVectors

# Build rule for target.
3dVectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3dVectors
.PHONY : 3dVectors

# fast build rule for target.
3dVectors/fast:
	$(MAKE) -f CMakeFiles/3dVectors.dir/build.make CMakeFiles/3dVectors.dir/build
.PHONY : 3dVectors/fast

Mesh.o: Mesh.cpp.o

.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i

.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s

.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

Particle.o: Particle.cpp.o

.PHONY : Particle.o

# target to build an object file
Particle.cpp.o:
	$(MAKE) -f CMakeFiles/ExtraterrestrialBodies.dir/build.make CMakeFiles/ExtraterrestrialBodies.dir/Particle.cpp.o
.PHONY : Particle.cpp.o

Particle.i: Particle.cpp.i

.PHONY : Particle.i

# target to preprocess a source file
Particle.cpp.i:
	$(MAKE) -f CMakeFiles/ExtraterrestrialBodies.dir/build.make CMakeFiles/ExtraterrestrialBodies.dir/Particle.cpp.i
.PHONY : Particle.cpp.i

Particle.s: Particle.cpp.s

.PHONY : Particle.s

# target to generate assembly for a file
Particle.cpp.s:
	$(MAKE) -f CMakeFiles/ExtraterrestrialBodies.dir/build.make CMakeFiles/ExtraterrestrialBodies.dir/Particle.cpp.s
.PHONY : Particle.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

matrix.o: matrix.cpp.o

.PHONY : matrix.o

# target to build an object file
matrix.cpp.o:
	$(MAKE) -f CMakeFiles/3x3Matrices.dir/build.make CMakeFiles/3x3Matrices.dir/matrix.cpp.o
.PHONY : matrix.cpp.o

matrix.i: matrix.cpp.i

.PHONY : matrix.i

# target to preprocess a source file
matrix.cpp.i:
	$(MAKE) -f CMakeFiles/3x3Matrices.dir/build.make CMakeFiles/3x3Matrices.dir/matrix.cpp.i
.PHONY : matrix.cpp.i

matrix.s: matrix.cpp.s

.PHONY : matrix.s

# target to generate assembly for a file
matrix.cpp.s:
	$(MAKE) -f CMakeFiles/3x3Matrices.dir/build.make CMakeFiles/3x3Matrices.dir/matrix.cpp.s
.PHONY : matrix.cpp.s

quaternion.o: quaternion.cpp.o

.PHONY : quaternion.o

# target to build an object file
quaternion.cpp.o:
	$(MAKE) -f CMakeFiles/Quaternions.dir/build.make CMakeFiles/Quaternions.dir/quaternion.cpp.o
.PHONY : quaternion.cpp.o

quaternion.i: quaternion.cpp.i

.PHONY : quaternion.i

# target to preprocess a source file
quaternion.cpp.i:
	$(MAKE) -f CMakeFiles/Quaternions.dir/build.make CMakeFiles/Quaternions.dir/quaternion.cpp.i
.PHONY : quaternion.cpp.i

quaternion.s: quaternion.cpp.s

.PHONY : quaternion.s

# target to generate assembly for a file
quaternion.cpp.s:
	$(MAKE) -f CMakeFiles/Quaternions.dir/build.make CMakeFiles/Quaternions.dir/quaternion.cpp.s
.PHONY : quaternion.cpp.s

vect.o: vect.cpp.o

.PHONY : vect.o

# target to build an object file
vect.cpp.o:
	$(MAKE) -f CMakeFiles/3dVectors.dir/build.make CMakeFiles/3dVectors.dir/vect.cpp.o
.PHONY : vect.cpp.o

vect.i: vect.cpp.i

.PHONY : vect.i

# target to preprocess a source file
vect.cpp.i:
	$(MAKE) -f CMakeFiles/3dVectors.dir/build.make CMakeFiles/3dVectors.dir/vect.cpp.i
.PHONY : vect.cpp.i

vect.s: vect.cpp.s

.PHONY : vect.s

# target to generate assembly for a file
vect.cpp.s:
	$(MAKE) -f CMakeFiles/3dVectors.dir/build.make CMakeFiles/3dVectors.dir/vect.cpp.s
.PHONY : vect.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... ExtraterrestrialBodies"
	@echo "... Mesh"
	@echo "... Quaternions"
	@echo "... 3x3Matrices"
	@echo "... 3dVectors"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... quaternion.o"
	@echo "... quaternion.i"
	@echo "... quaternion.s"
	@echo "... vect.o"
	@echo "... vect.i"
	@echo "... vect.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

